Algoritmo "Q7"

Var
   n1, n2 : Caracter
   i1, i2 : Inteiro
   p1, p2 : Real

Inicio
      escreva("Digite seu nome1: ")
      leia(n1)
      escreva("Digite seu idade1: ")
      leia(i1)
      escreva("Digite seu peso1: ")
      leia(p1)
      escreva("Digite seu nome2: ")
      leia(n1)
      escreva("Digite seu idade2: ")
      leia(1i)
      escreva("Digite seu peso2: ")
      leia(p1)
      
      escreva("Pessoa1: ", n1, i1, p1)
      escreva("Pessoa1: ", n1, i1, p1)

Fimalgoritmo